"""update column in  profiledata table

Revision ID: 0cc500776eef
Revises: 8c8ac97afb4f
Create Date: 2023-05-12 16:41:05.451208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc500776eef'
down_revision = '8c8ac97afb4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
