"""create profiledata table

Revision ID: 3725d5393c19
Revises: c68f018761bf
Create Date: 2023-05-12 16:47:46.736827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3725d5393c19'
down_revision = 'c68f018761bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiledata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorname', sa.String(), nullable=False),
    sa.Column('doctor_image', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('number_of_patients', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiledata')
    # ### end Alembic commands ###
