"""update profiledata table 

Revision ID: 48d0c48787e8
Revises: 773fc41f7c60
Create Date: 2023-05-07 19:13:56.293729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d0c48787e8'
down_revision = '773fc41f7c60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiledata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctorname', sa.String(), nullable=False),
    sa.Column('doctor_image', sa.LargeBinary(), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('number_of_patients', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiledata')
    # ### end Alembic commands ###
