"""Add delete cascade to Patient-MedicalRecord relationship

Revision ID: 588d38aa935b
Revises: 2c90b954faa0
Create Date: 2023-04-14 02:38:21.013274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588d38aa935b'
down_revision = '2c90b954faa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
