""" add column to verification_codes table

Revision ID: 773fc41f7c60
Revises: db895fea460d
Create Date: 2023-04-16 02:35:09.200815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773fc41f7c60'
down_revision = 'db895fea460d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_codes', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_codes', 'expires_at')
    # ### end Alembic commands ###
