"""update column in  profiledata table

Revision ID: 8c8ac97afb4f
Revises: 48d0c48787e8
Create Date: 2023-05-12 16:38:41.082397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8ac97afb4f'
down_revision = '48d0c48787e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
